version: "3.9"

services:
  server-app-db:
    restart: always
    image: postgres
    container_name: server-app-db
    environment:
      POSTGRES_DB: ifuture
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yNh4(q-8Vi0l
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - C:/../src/main/resources/data.sql:/docker-entrypoint-initdb.d
      - C:/../src/main/resources/schema.sql:/docker-entrypoint-initdb.d

  server-app:
    build: .
    container_name: server-app
    ports:
      - "8080:8080"
    depends_on:
      - server-app-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://server-app-db:5432/
      SPRING_DATASOURCE_USER: postgres
      SPRING_DATASOURCE_PASSWORD: yNh4(q-8Vi0l