server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ifuture
    username: postgres
    password: yNh4(q-8Vi0l
  jpa:
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always

logging:
  level:
    org.springframework: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  file:
    name: logs/app.log
  logback:
    rollingpolicy:
      max-file-size: 15MB

